Solved issue 3
Van10000/liquid-log pull request #3
Opened 2018-10-17 00:59 UTC by Van10000

Я не знаю до какого момента сегодняшнего дня нужно сдать задание. Надеюсь, ещё не слишком поздно.
@d0k1 @ykalemi @etitov

2018-10-17 13:11 UTC, gallyamb requested changes

2018-10-17 13:11 UTC, gallyamb commented on src/main/java/ru/naumen/sd40/log/parser/App.java
> +    private static HashMap<String, Supplier<TimeParser>> RegisterTimeParsers(String timeZone, String log)
```suggestion
    private static HashMap<String, Supplier<TimeParser>> registerTimeParsers(String timeZone, String log)
```

2018-10-17 13:11 UTC, gallyamb commented on src/main/java/ru/naumen/sd40/log/parser/App.java
> +        try (BufferedReader br = new BufferedReader(new FileReader(log), 32 * 1024 * 1024))
`32 * 1024 * 1024` - предлагаю вынести в константу с понятным именем, вместо использования magic number

2018-10-17 13:11 UTC, Gebon commented on src/main/java/ru/naumen/sd40/log/parser/NumberUtils.java
> +    public static long alignTo(long number, long align)
В чем суть данного метода?

2018-10-17 13:11 UTC, Gebon commented on src/main/java/ru/naumen/sd40/log/parser/data/DataParser.java
> +    void parse(String line, DataSet dataSet) throws ParseException;
А откуда уверенность, что абсолютно все данные помещаются в строку?

2018-10-17 13:11 UTC, Gebon commented on src/main/java/ru/naumen/sd40/log/parser/dataset/GCParser.java
> +public class GCParser
Как-то слишком много слов `parser` в коде. Они точно все являются парсерами? Можно ли как-то разграничить на уровне наименования различные действия?

2018-10-17 13:11 UTC, Gebon commented on src/main/java/ru/naumen/sd40/log/parser/dataset/GCParser.java
> +public class GCParser
Может быть, некоторая часть абстракции вообще не нужна?

2018-10-17 13:11 UTC, Gebon commented on src/main/java/ru/naumen/sd40/log/parser/dataset/TopParser.java
> +        Matcher la = Pattern.compile(".*load average:(.*)").matcher(line);
Компиляция паттерна - трудоемкая операция. Предлагаю вынести в поле

2018-10-17 18:05 UTC, Van10000 commented on src/main/java/ru/naumen/sd40/log/parser/NumberUtils.java
> +    public static long alignTo(long number, long align)
Выравнить число по какой-то сетке (округлив вниз).
Собственно, мы в коде выравниваем время по 5 минутам.

Мне казалось, достаточно понятный метод.

2018-10-17 18:10 UTC, Van10000 commented on src/main/java/ru/naumen/sd40/log/parser/data/DataParser.java
> +    void parse(String line, DataSet dataSet) throws ParseException;
Все данные в строчку не помещаются, но мы просто парсим их построчно.
Ну и в конце концов в строчку можно и несколько строчек положить, если сильно нужно.

Я в общем не очень понял в чём именно проблема.

2018-10-17 18:18 UTC, Van10000 commented on src/main/java/ru/naumen/sd40/log/parser/dataset/GCParser.java
> +public class GCParser
Нет, не все.
Всё как раз разбито на папочки по логике.
Есть то, что реализует интерфейс DataParser - это высокоуровневая штука, которая дёргает в DataSet-е нужные методы, в соответствии с тем какие именно данные мы парсим.

А есть внутри DataSet-а классы, которые собственно занимаются парсингом и хранят в себе результат. Они никакой интерфейс не реализуют (потому что нам нигде не нужна над ними абстракция).

По хорошему, то что называется интерфейсом DataParser возможно стоило бы переименовать, потому что эта абстракция не занимается собственно парсингом, а лишь решает какие парсеры вызвать для конкретного mode.
Просто в задаче просили сделать именно интерфейс DataParser, а у меня он по смыслу получился немножко другой (хотя проблемы, поставленные в задании, я считаю, я решил).

Норм будет если мы переименуем интерфейс DataParser скажем в DataSetPopulator?
Он занимается тем, что добавляет в DataSet новую строчку (зная какими именно парсерами из DataSet её нужно распарсить)

2018-10-17 23:02 UTC, Van10000 commented on src/main/java/ru/naumen/sd40/log/parser/dataset/TopParser.java
> +        Matcher la = Pattern.compile(".*load average:(.*)").matcher(line);
Ну на самом деле, я этот код не менял. Это простое скопированный код, который использовался изначально при парсинге. Если весь код проекта от таких мелочей чистить - очень много наберётся. Ну ладно, поправлю.

2018-10-17 23:11 UTC, Van10000 commented
Я в окобщем поправил код в части мест, замечания по которой мне были понятны и с которыми я был согласен. По остальному жду ответа.

2018-10-18 06:33 UTC, Gebon commented on src/main/java/ru/naumen/sd40/log/parser/NumberUtils.java
> +    public static long alignTo(long number, long align)
Тогда это все же не `alignTo`, а какой-нибудь `floorUpToNthDigit`

Align подошел бы в контексте leftPad и тому подобному. Что скажешь?

2018-10-18 06:35 UTC, Gebon commented on src/main/java/ru/naumen/sd40/log/parser/data/DataParser.java
> +    void parse(String line, DataSet dataSet) throws ParseException;
Имелось в виду, откуда уверенность, что все данные, нужные для одной итерации парсинга, всегда лежат в одной строке. Сейчас по логике всего кода видно, что данные считываются построчно и отдаются в этот парсер

2018-10-18 17:55 UTC, Van10000 commented on src/main/java/ru/naumen/sd40/log/parser/NumberUtils.java
> +    public static long alignTo(long number, long align)
Но он ведь не до знака округляет.
Скажем, мы можем выравнивать по сетке чисел кратным 6-ти.
Тогда число 10 выровняется на 6. А число 13 - на 12.
Не понял про leftPad.

2018-10-18 18:01 UTC, Van10000 commented on src/main/java/ru/naumen/sd40/log/parser/data/DataParser.java
> +    void parse(String line, DataSet dataSet) throws ParseException;
Ну да, данные считываются построчно и парсер их построчно обрабатывает. Мы у парсера много раз вызываем этот метод.

Ну то есть как это работает:
Мы прочитали строчку, распарсили время, выравняли его до 5-ти минут, далее если для этого пятиминутного блока ещё не было DataSetPopulator-а (теперь он так называется) - создали. А если был - то взяли тот, который был. И передали ему очередную строчку.
Соответственно, конечно же это абсолютно возможная ситуация, что у одного Populator-а вызовется метод много раз.

Я по прежнему не понимаю суть проблемы.

2018-10-19 04:22 UTC, gallyamb commented on src/main/java/ru/naumen/sd40/log/parser/data/DataParser.java
> +    void parse(String line, DataSet dataSet) throws ParseException;
Вот у тебя файл для какого-то режима X:
```
19.10.2018 09:20 some message with
newline ERROR
```

В данном случае ты не можешь считать одну строку и только ее распарсить. Данные будут некорректны

Проблема понятна?

2018-10-19 04:29 UTC, Gebon commented on src/main/java/ru/naumen/sd40/log/parser/NumberUtils.java
> +    public static long alignTo(long number, long align)
Про leftPad можно погуглить

Эта функция занимается ровно округлением до максимального целого числа, которое меньше заданного и кратно аргументу. Math.floor - это точно такая же функция, только число кратности в нем 1. И именно потому что это просто частный случай, я предлагаю назвать эту функцию `floor...`. Да, не `floorUpToNthDigit`, но что-то явно похожее

А align это про другое в большинстве случаях использования этого слова

2018-10-19 07:15 UTC, Gebon commented on src/main/java/ru/naumen/sd40/log/parser/data/DataParser.java
> +    void parse(String line, DataSet dataSet) throws ParseException;
Тут я неправильно выразил мысль, моя вина

Discussion можно считать закрытым

2018-10-19 07:18 UTC, gallyamb requested changes

2018-10-19 07:18 UTC, Gebon commented on src/main/java/ru/naumen/sd40/log/parser/App.java
> +                dataSetPopulator.populate(line, data.computeIfAbsent(key, k -> new DataSet()));
Судя по тому, что было в предыдущей версии, top имеет другой формат парсинга

Т.е. там не подходит условие `if (time == 0) continue`. Как в текущей версии учитывается эта особенность?

2018-10-19 07:19 UTC, Gebon commented on src/main/java/ru/naumen/sd40/log/parser/NumberUtils.java
> +    public static long alignTo(long number, long align)
Тем не менее, это, конечно же, не замечание, которое нужно поправить, а просто рекомендация по именованию, которой можно и не следовать

2018-10-19 07:34 UTC, gallyamb approved these changes
Увидел, как обрабатывается время в top. Правда, я думаю, что это плохо, что TopTimeParser знает, что нужно вернуть 0 при первом парсинге, т.к. в этой строке нет данных

2018-10-19 13:20 UTC, Van10000 commented on src/main/java/ru/naumen/sd40/log/parser/NumberUtils.java
> +    public static long alignTo(long number, long align)
По leftPad гуглится только добивание строки какими-нибудь символами слева до нужной длины. Я не смог нагуглить нигде чтобы был именно тот смысл о котором ты пишешь. 
В рассуждениях про floor есть смысл. Наверное, подумаю как это можно назвать и, возможно, переименую.

2018-10-19 13:23 UTC, Van10000 commented
Нет, он возвращает 0 не при первом парсинге, а при парсинге каждой строчки, в которой есть информация о времени. То есть, есть строчки со временем и с данными. Кажется что это всё-таки не какой-то костыль "верни 0 при первом парсинге" а вполне осмысленная логика.
Ну и как минимум раньше по сути логика была такой же. Суть задачи ведь в том чтобы отрефакторить, а не переписать.

2018-10-19 14:14 UTC, Gebon commented
При первом парсинге, или для каждой строчки со временем - не важно. Важно то, что этот компонент знает и подстраиваться под логику на уровне абстракции выше. Т.е. не вызывающий код знает, как работать с этим компонентом, а компонент знает, как работает вызывающий код. Это довольно шаткая конструкция. Если изменится вызывающий код или код парсера, все может сломаться

По факту ведь это неявный интерфейс. Вот если его сделать явным, кмк, будет совсем другое

2018-10-20 17:22 UTC, Van10000 commented
Ясно. Например, возвращать Optional<long>.
Кажется, хорошая идея.

2018-10-20 17:38 UTC, merged