Almost solved issue 6
Van10000/liquid-log pull request #6
Opened 2018-11-06 20:38 UTC by Van10000

Код написан, однако он сейчас падает, проблема с внедрением зависимостей.

Суть в том, что в некоторых местах объект хочется с одной стороны создавать руками (передавая ему какие-то аргументы, которые нельзя заinject-ить), с другой стороны часть зависимостей объекта хотелось бы всё-таки получать из DIContainer-а.
Пример - класс InfluxConnector, которому нужны текстовые параметры, переданные пользователем, а ещё InfluxDAO, который не хотелось бы создавать руками.

Собственно, решением этой проблемы, насколько я понимаю, является Autowired поле (как я и попытался сделать в InfluxConnector-е).
Как оказалось, это не так просто, однако [здесь](https://stackoverflow.com/questions/3813588/how-to-inject-dependencies-into-a-self-instantiated-object-in-spring) написано что возможно. Я попытался сделать всё по инструкции в предпоследнем ответе. Однако, всё равно в Autowired-поле null.

Может, подскажете в чём именно проблема?
Или, может, предложите хорошую альтернативу как можно сделать по-другому.

@d0k1 @ykalemi @etitov

2018-11-07 07:22 UTC, d0k1 requested changes
где конкрентно происходит проблема с инъектицией зависимостей в готовый экземпляр какого-либо класса?

2018-11-07 07:22 UTC, d0k1 commented on src/main/java/ru/naumen/perfhouse/PerfhouseApplication.java
> +@EnableSpringConfigured
зачем?

2018-11-07 10:30 UTC, Van10000 commented on src/main/java/ru/naumen/perfhouse/PerfhouseApplication.java
> +@EnableSpringConfigured
Я в первом сообщении оставил ссылку на stack overflow. Там есть инструкция в предпоследнем посте как сделать, чтобы всё заработало. Собственно, в этой инструкции была такая строчка.

2018-11-07 10:32 UTC, Van10000 commented
Есть 2 принципиально разные ситуации:
1) Объект создаётся Spring-ом.
2) Объект создаётся мной через new.

Вот во втором случае если у объекта есть Autowired-поля - в них попадает null.
Зачем мне такое надо описал в первом сообщении.

Примеры классов где такая проблема возникает:
- InfluxConnector
- все Populator-ы

2018-11-07 10:44 UTC, d0k1 commented
Благодарю за уточнение, но я предложенную инструкцию прочитал. И как читатель stackoverflow я рекомендую ориентироваться на ответы с зеленой "галочкой" слева - там наиболее вероятно правильный ответ. И на самом деле, так и есть и в Вашем случае.

`@Configurable` и прочая магия AOP  мне кажется излишняя. Достаточно @Component.
Если же экземпляр класс будет всегда создаваться через new то и аннотация спринга нал классом излишняя.

Вам нужно найти экземпляр BeanFactory и сделать так, как предлагается в ответе 
`beanFactory.autowireBean(this);` в констуркторе.

один из возможных варинатов - получить экземпляр org.springframework.web.context.WebApplicationContext и вызвать getAutowireCapableBeanFactory()

Пробовали ли так?

2018-11-07 17:57 UTC, Van10000 commented
Всё оказалось не так просто (сложность была в том, чтобы получить BeanFactory в статическом контексте). Но в целом решение выглядит не так плохо.

2018-11-08 07:29 UTC, d0k1 commented
Поясните еще пожалуйста почему Вам было необходимо использовать new? почему просто нельзя было инжектирвоать Spring Bean?

2018-11-08 10:41 UTC, Van10000 commented
Потому что InfluxConnector хочет получать помимо зависимостей некоторые аргументы, введённые пользователем.
А Populator-ы хотелось просто руками зарегистрировать, чтобы потом выбрать нужный по строчке. Хотя сейчас я осознал, что можно было бы зарегистрировать их, назвав этой самой строчкой. И тогда получилось бы инъектировать. 
Но возможно об этом как раз говориться в следующем задании. У меня ведь роль Parser-а выполняет Populator. Именно эта штука реализует какой-то интерфейс и используется на высоком уровне.

2018-11-08 10:49 UTC, d0k1 approved these changes
задание принято

2018-11-12 22:46 UTC, merged